config/routes.rb
Rails.application.routes.draw do
  post 'loan_application/create', to: 'loan_application#create'
  root 'loan_application#new'

  get 'loan_application/new', to: 'loan_application#new'
  get 'loan_application/show/:id', to: 'loan_application#show', as: 'loan_application_show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/loan_application.rb
class LoanApplication < ApplicationRecord
	MAX_LOAN_AMOUNT_ON_PURCHASE_PRICE = 0.90 # 90% of Purchase Price
	MAX_LOAN_AMOUNT_ON_ARV = 0.70 # 70% of ARV

	# Extesnsions
	strip_attributes

	# Validations
	validates :target_property, :loan_term, :purchase_price, :estimated_budget_repair,
  					:after_repair_value, :first_name, :email, :phone_number, presence: true

  validates :loan_term, numericality: { only_integer: true, greater_than: 0,
                                        less_than_or_equal_to: 12 }

  validates :purchase_price, :estimated_budget_repair, :after_repair_value,
            numericality: { only_integer: true, greater_than: 0 }

  validates :phone_number, presence: true, format: {
	  with: /\A(\+\d{1,3}\s?)?\(?\d{1,4}\)?[-.\s]?\d{1,4}[-.\s]?\d{1,4}\z/,
	  message: "should be a valid phone number"
	}

	# callbacks
	before_save :initiate_loan_and_profit
	after_commit :send_email, on: :create

	def full_name
		"#{first_name} #{last_name}"
	end

	def max_loan_on_purchase_price
		MAX_LOAN_AMOUNT_ON_PURCHASE_PRICE * purchase_price
	end

	def max_loan_on_arv
		MAX_LOAN_AMOUNT_ON_ARV * after_repair_value
	end

	def initiate_loan_and_profit
		self.loan_amount = [max_loan_on_purchase_price, max_loan_on_arv].min
		calculated_proft = Loan::CalculateProfitService.new(self).call
		self.estimated_profit = calculated_proft[:estimated_profit]
		self.return_rate = calculated_proft[:return_rate]
	end

	def phone_number_with_country_code
		"#{country_code}#{phone_number}"
	end

	def send_email
    LoanApplicationMailer.estimated_profit_mail(self.id).deliver_later
	end
end

app/models/loan_profit.rb
class LoanProfit < ApplicationRecord
	# Extesnsions
	strip_attributes

	# Validations
	validates :target_property, :loan_term, :purchase_price, :estimated_budget_repair,
  					:after_repair_value, :first_name, :email, :phone_number, presence: true

  validates :loan_term, numericality: { only_integer: true, greater_than: 0,
                                        less_than_or_equal_to: 12 }

  validates :purchase_price, :estimated_budget_repair, :after_repair_value,
            numericality: { only_integer: true, greater_than: 0 }

  validates :phone_number, presence: true, format: {
	  with: /\A(\+\d{1,3}\s?)?\(?\d{1,4}\)?[-.\s]?\d{1,4}[-.\s]?\d{1,4}\z/,
	  message: "should be a valid phone number"
	}

	def full_name
		"#{first_name} #{last_name}"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/loan_application_controller.rb
class LoanApplicationController < ApplicationController
  before_action :set_loan_application, only: [:show] 

  def create
    @loan_application = LoanApplication.new(loan_application_params)

    if @loan_application.save
      flash[:success] = ['Loan application was successfully created.']
      redirect_to loan_application_show_path(@loan_application)
    else
      flash.now[:error] = @loan_application.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @loan_application = LoanApplication.new
  end

  def show
    redirect_to root_path, flash: { error: ['Loan application not found.'] } unless @loan_application
  end

  private

  def loan_application_params
    params.require(:loan_application).permit(:target_property, :loan_term, :purchase_price,
                                             :estimated_budget_repair, :after_repair_value,
                                             :first_name, :last_name, :email, :phone_number,
                                             :country_code)
  end

  def set_loan_application
    @loan_application = LoanApplication.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
# app/helpers/application_helper.rb

module ApplicationHelper
  def flash_class(type)
    case type
    when 'notice'
      "bg-blue-100 border-t-4 border-blue-500 text-blue-700 px-4 py-3 rounded relative"
    when 'alert'
      "bg-red-100 border-t-4 border-red-500 text-red-700 px-4 py-3 rounded relative"
    when 'error'
      "bg-yellow-100 border-t-4 border-yellow-500 text-yellow-700 px-4 py-3 rounded relative"
    else
      "bg-green-100 border-t-4 border-green-500 text-green-700 px-4 py-3 rounded relative"
    end
  end

  def flash_title(type)
    case type
    when 'notice'
      "Notice!"
    when 'alert'
      "Alert!"
    when 'error'
      "Error!"
    else
      "Success!"
    end
  end
end

app/helpers/loan_profit_helper.rb
module LoanProfitHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoanProfitCalculator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,container-queries"></script>

    <style type="text/tailwindcss">
      @layer utilities {
        .content-auto {
          content-visibility: auto;
        }
      }
  </style>
  </head>

  <body class="bg-custom-light-gray">
    <%= render 'shared/header' %>
    <%= render 'shared/flash_messages' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoanProfitCalculator</title>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= wicked_pdf_stylesheet_link_tag "pdf" %>
  </head>
  <body>
    <div id="header">
      <!--= wicked_pdf_image_tag 'thumbnail.png', height: "30", width: "auto"-->
    </div>
    <%= yield %>
  </body>
</html>

app/views/loan_application/_estimated_profit.html.erb
<div style="text-align: center;">
  <h1 style="font-size: 24px; font-weight: bold; margin-bottom: 10px;">Loan Profit Calculation Details</h1>
  <p style="margin-bottom: 20px;">Review the details below</p>

  <table style="margin: 0 auto; border-collapse: collapse; width: 80%; border: 1px solid #ccc;">
    <thead style="background-color: #f3f4f6;">
      <tr>
        <th style="border: 1px solid #ccc; padding: 8px;">Field</th>
        <th style="border: 1px solid #ccc; padding: 8px;">Value</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td style="border: 1px solid #ccc; padding: 8px;">Your Name</td>
        <td style="border: 1px solid #ccc; padding: 8px;"><%= loan_application.full_name %></td>
      </tr>
      <tr>
        <td style="border: 1px solid #ccc; padding: 8px;">Max Loan Amount</td>
        <td style="border: 1px solid #ccc; padding: 8px;">£ <%= loan_application.loan_amount %></td>
      </tr>
      <tr>
        <td style="border: 1px solid #ccc; padding: 8px;">Estimated Profit</td>
        <td style="border: 1px solid #ccc; padding: 8px;">£ <%= loan_application.estimated_profit %></td>
      </tr>
      <tr>
        <td style="border: 1px solid #ccc; padding: 8px;">Return Rate</td>
        <td style="border: 1px solid #ccc; padding: 8px;"><%= loan_application.return_rate %>%</td>
      </tr>
      <!-- Add more rows as needed -->
    </tbody>
  </table>
</div>

app/views/loan_application/calculate_profit.html.erb
<h1>Loan#calculate_profit</h1>
<p>Find me in app/views/loan/calculate_profit.html.erb</p>

app/views/loan_application/new.html.erb
<!-- app/views/loan_requests/_form.html.erb -->
<div class="flex items-center justify-center min-h-screen">
  <div class="my-2 w-full sm:w-10/12 md:w-8/12 lg:w-7/12 xl:w-6/12 bg-white p-8 shadow-md rounded-lg">
    <%= form_with(model: @loan_application, url: loan_application_create_path, method: :post, local: true, class: "space-y-1 bg-gray-100 p-6 shadow-md rounded-md") do |form| %>

      <%= form.label :target_property, 'Target Property*', class: "block text-md font-medium" %>
      <span class="font-medium text-xs block md:inline-block md:ml-0 md:mt-1"> (Address, City, State, & Zip for your target property) </span>
      <%= form.text_field :target_property, required: true, class: "mt-1 block w-full rounded-md border border-gray-300 p-2 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>

      <%= form.label :loan_term, 'Loan Term*', class: "block text-md font-medium" %>
      <span class="font-medium text-xs block md:inline-block md:ml-0 md:mt-1">(How many months do you want the loan for, up to 12)? </span>
      <%= form.number_field :loan_term, required: true, min: 1, max: 12, step: 1, class: "mt-1 block w-full rounded-md border border-gray-300 p-2 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", oninput: "restrictToPositiveIntegers(event)" %>
      <small id="loan_term_error" class="text-red-600" aria-live="polite"></small>

      <%= form.label :purchase_price, 'Purchase Price*', class: "block text-md font-medium" %>
      <span class="font-medium text-xs block md:inline-block md:ml-0 md:mt-1" >
        What are you purchasing the property for? Please include any assignment fee.
        <br>
        *Our sample term sheet will set a maximum loan-to-cost of 90%.
      </span>
      <%= form.number_field :purchase_price, required: true, min: 1, class: "mt-1 block w-full rounded-md border border-gray-300 p-2 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", oninput: "restrictToPositiveIntegers(event)" %>
      <small id="purchase_price_error" class="text-red-600 flex items-center" aria-live="polite"></small>

      <%= form.label :estimated_budget_repair, 'Estimated Repair Budget*', class: "block text-md font-medium" %>
      <span class="font-medium text-xs block md:inline-block md:ml-0 md:mt-1">
        (Full budget expected to rehab the property.)
      </span>
      <%= form.number_field :estimated_budget_repair, required: true, min: 1, class: "mt-1 block w-full rounded-md border border-gray-300 p-2 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", oninput: "restrictToPositiveIntegers(event)" %>
      <small id="repair_budget_error" class="text-red-600 flex items-center" aria-live="polite"></small>

      <%= form.label :after_repair_value, 'After Repair Value*', class: "block text-md font-medium" %>
      <span class="font-medium text-xs block md:inline-block md:ml-0 md:mt-1">
        What do you think the property's market value will be when you complete the rehab?
        <br>
        *Our sample term sheet will set a maximum loan-to-value of 70%
      </span>
      <%= form.number_field :after_repair_value, required: true, min: 1, class: "mt-1 block w-full rounded-md border border-gray-300 p-2 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", oninput: "restrictToPositiveIntegers(event)" %>
      <small id="after_repair_value_error" class="text-red-600 flex items-center" aria-live="polite"></small>

      <%= form.label :first_name, 'First Name', class: "block text-md font-medium" %>
      <%= form.text_field :first_name, required: true, class: "mt-1 block w-full rounded-md border border-gray-300 p-2 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>

      <%= form.label :last_name, 'Last Name', class: "block text-md font-medium" %>
      <%= form.text_field :last_name, class: "mt-1 block w-full rounded-md border border-gray-300 p-2 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>

      <%= form.label :email, 'Email', class: "block text-md font-medium" %>
      <%= form.email_field :email, required: true, class: "mt-1 block w-full rounded-md border border-gray-300 p-2 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>

      <%= form.label :phone_number, 'Phone', class: "block text-md font-medium" %>
     

      <div class="mt-2 flex">
        <div class="relative">
          <%= form.select :country_code, options_for_select([["+1 (US)", "+1"]]), { prompt: 'Select country code' }, required: true, class: 'rounded-l-md border border-gray-300 p-2 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm' %>
        </div>
        <div class="relative flex-1 ml-2">
          <%= form.text_field :phone_number, required: true, class: "block w-full rounded-r-md border border-gray-300 p-2 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", inputmode: "numeric",
            pattern: '\d{3}-?\d{3}-?\d{4}', placeholder: "Enter phone number (e.g., 123-456-7890 or 1234567890)" %>
        </div>
      </div>

      <div class="my-4">
        <%= form.button "Calculate Profit", class: "mt-6 flex w-full justify-center rounded-md custom-button-color px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:custom-button-color focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600", submit: true, data: {disable_with: "Please wait..."}%>
      </div>
    <% end %>
  </div>
</div>


<script>

  // Function to allow only positive integers in number fields
    function restrictToPositiveIntegers(event) {
      const inputValue = event.target.value;
      // Remove any non-digit characters
      const sanitizedValue = inputValue.replace(/[^\d]/g, '');
      // Update the field value
      event.target.value = sanitizedValue;

      // Show error if input is not a positive integer
      const errorElement = document.getElementById(`${event.target.id}_error`);
      if (!/^[1-9]\d*$/.test(sanitizedValue)) {
        errorElement.textContent = "Numbers only please";
      } else {
        errorElement.textContent = "";
      }
    }
</script>

app/views/loan_application/show.html.erb
<div class="flex items-center justify-center min-h-screen">
  <div class="text-center">
    <h1 class="text-2xl font-semibold mb-4">Thanks, <%= @loan_application.full_name %><span class="text-gray-900"></span>! Here are those figures we promised.</h1>
    <p class="text-lg mb-6">And again, check your email for the Longleaf term sheet.</p>
    <div class="text-gray-700 mt-8">
      <p class="text-xl">Your Estimated Profit: <span class="font-bold">£ <%= @loan_application.estimated_profit %></span></p>
      <p class="text-xl">Return Rate: <span class="font-bold"><%= @loan_application.return_rate %>%</span></p>
    </div>
    <div class="mt-8">
      <%= button_to 'Calculate Again!', loan_application_new_path, method: :get, class: "py-2.5 px-5 me-2 mb-2 text-sm font-medium justify-center rounded-md custom-button-color px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:custom-button-color focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600"%>
    </div>
  </div>
</div>

app/views/loan_profit/new.html.erb
<!-- app/views/loan_requests/_form.html.erb -->

<div class="custom-app-color text-white py-4">
  <div class="container mx-auto px-4">
    <h2 class="text-2xl font-semibold font-bold">Request a Loan</h2>
  </div>
</div>

<div class="flex items-center justify-center min-h-screen">
  <div class="my-2 w-full sm:w-10/12 md:w-8/12 lg:w-7/12 xl:w-6/12 bg-white p-8 shadow-md rounded-lg">
    <%= form_with(model: @loan_profit, url: loan_profit_create_path, method: :post, local: true, class: "space-y-1 bg-gray-100 p-6 shadow-md rounded-md") do |form| %>

      <%= form.label :target_property, 'Target Property*', class: "block text-md font-medium" %>
      <span class="font-medium text-xs block md:inline-block md:ml-0 md:mt-1"> (Address, City, State, & Zip for your target property) </span>
      <%= form.text_field :target_property, required: true, class: "mt-1 block w-full rounded-md border border-gray-300 p-2 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>

      <%= form.label :loan_term, 'Loan Term*', class: "block text-md font-medium" %>
      <span class="font-medium text-xs block md:inline-block md:ml-0 md:mt-1">(How many months do you want the loan for, up to 12)? </span>
      <%= form.number_field :loan_term, required: true, min: 1, max: 12, step: 1, class: "mt-1 block w-full rounded-md border border-gray-300 p-2 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", oninput: "restrictToPositiveIntegers(event)" %>
      <small id="loan_term_error" class="text-red-600" aria-live="polite"></small>

      <%= form.label :purchase_price, 'Purchase Price*', class: "block text-md font-medium" %>
      <span class="font-medium text-xs block md:inline-block md:ml-0 md:mt-1" >
        What are you purchasing the property for? Please include any assignment fee.
        <br>
        *Our sample term sheet will set a maximum loan-to-cost of 90%.
      </span>
      <%= form.number_field :purchase_price, required: true, min: 1, class: "mt-1 block w-full rounded-md border border-gray-300 p-2 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", oninput: "restrictToPositiveIntegers(event)" %>
      <small id="purchase_price_error" class="text-red-600 flex items-center" aria-live="polite"></small>

      <%= form.label :estimated_budget_repair, 'Estimated Repair Budget*', class: "block text-md font-medium" %>
      <span class="font-medium text-xs block md:inline-block md:ml-0 md:mt-1">
        (Full budget expected to rehab the property.)
      </span>
      <%= form.number_field :estimated_budget_repair, required: true, min: 1, class: "mt-1 block w-full rounded-md border border-gray-300 p-2 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", oninput: "restrictToPositiveIntegers(event)" %>
      <small id="repair_budget_error" class="text-red-600 flex items-center" aria-live="polite"></small>

      <%= form.label :after_repair_value, 'After Repair Value*', class: "block text-md font-medium" %>
      <span class="font-medium text-xs block md:inline-block md:ml-0 md:mt-1">
        What do you think the property's market value will be when you complete the rehab?
        <br>
        *Our sample term sheet will set a maximum loan-to-value of 70%
      </span>
      <%= form.number_field :after_repair_value, required: true, min: 1, class: "mt-1 block w-full rounded-md border border-gray-300 p-2 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", oninput: "restrictToPositiveIntegers(event)" %>
      <small id="after_repair_value_error" class="text-red-600 flex items-center" aria-live="polite"></small>

      <%= form.label :first_name, 'First Name', class: "block text-md font-medium" %>
      <%= form.text_field :first_name, required: true, class: "mt-1 block w-full rounded-md border border-gray-300 p-2 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>

      <%= form.label :last_name, 'Last Name', class: "block text-md font-medium" %>
      <%= form.text_field :last_name, class: "mt-1 block w-full rounded-md border border-gray-300 p-2 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>

      <%= form.label :email, 'Email', class: "block text-md font-medium" %>
      <%= form.email_field :email, required: true, class: "mt-1 block w-full rounded-md border border-gray-300 p-2 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>

      <%= form.label :phone_number, 'Phone', class: "block text-md font-medium" %>
     

      <div class="mt-2 flex">
        <div class="relative">
          <%= form.select :country_code, options_for_select([["+1 (US)", "+1"]]), { prompt: 'Select country code' }, required: true, class: 'rounded-l-md border border-gray-300 p-2 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm' %>
        </div>
        <div class="relative flex-1 ml-2">
          <%= form.text_field :phone_number, required: true, class: "block w-full rounded-r-md border border-gray-300 p-2 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", inputmode: "numeric",
            pattern: '\d{3}-?\d{3}-?\d{4}', placeholder: "Enter phone number (e.g., 123-456-7890 or 1234567890)" %>
        </div>
      </div>



      <div class="my-4">
        <%= form.submit "Submit", class: "mt-6 flex w-full justify-center rounded-md custom-button-color px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:custom-button-color focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600" %>
      </div>
    <% end %>
  </div>
</div>


<script>
  // Function to allow only positive integers in number fields
    function restrictToPositiveIntegers(event) {
      const inputValue = event.target.value;
      // Remove any non-digit characters
      const sanitizedValue = inputValue.replace(/[^\d]/g, '');
      // Update the field value
      event.target.value = sanitizedValue;

      // Show error if input is not a positive integer
      const errorElement = document.getElementById(`${event.target.id}_error`);
      if (!/^[1-9]\d*$/.test(sanitizedValue)) {
        errorElement.textContent = "Numbers only please";
      } else {
        errorElement.textContent = "";
      }
    }
</script>

app/views/loan_profit/show.html.erb
<div class="flex items-center justify-center min-h-screen">
  <div class="text-center">
    <h1 class="text-2xl font-semibold mb-4">Thanks, <%= @loan_profit.full_name %><span class="text-gray-900">name</span>! Here are those figures we promised.</h1>
    <p class="text-lg mb-6">And again, check your email for the Longleaf term sheet.</p>
    <div class="text-gray-700 mt-8">
      <p class="text-xl">Your Estimated Profit: <span class="font-bold">$<%= @profit[:estimated_profit] %></span></p>
      <p class="text-xl">Return Rate: <span class="font-bold"><%= @profit[:return_rate] %>%</span></p>
    </div>
  </div>
</div>

app/views/shared/_flash_messages.html.erb
<!-- app/views/shared/_flash_messages.html.erb -->
<% flash.each do |type, messages| %>
  <div class="<%= flash_class(type) %> px-4 py-3 rounded relative alert-dismissible" role="alert">
    <strong class="font-bold"><%= flash_title(type)%></strong>
    <% messages.each do |message| %>
      <div>
        <span class="block sm:inline"><%= message %></span>
        <button type="button" class="absolute top-0 bottom-0 right-0 px-4 py-3" onclick="this.parentElement.remove()">
          <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
            <title>Close</title>
            <path d="M14.36 5.64a.75.75 0 0 0-1.06 0L10 8.94 6.7 5.64a.75.75 0 0 0-1.06 1.06L8.94 10l-3.3 3.3a.75.75 0 1 0 1.06 1.06L10 11.06l3.3 3.3a.75.75 0 0 0 1.06-1.06L11.06 10l3.3-3.3a.75.75 0 0 0 0-1.06z"/>
          </svg>
        </button>
      </div>
    <% end %>
  </div>
<% end %>

<script>
  setTimeout(function() {
    document.querySelectorAll('.alert-dismissible').forEach(function(alert) {
      alert.remove();
    });
  }, 3000);
</script>

app/views/shared/_header.html.erb
<div class="custom-app-color text-white py-4">
  <div class="container mx-auto px-4">
    <h2 class="text-2xl font-semibold font-bold">Real Estate Profit and Return Calculator</h2>
  </div>
</div>